m09_13_01_django/killer_instagram/app_instagram/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "app_instagram"

urlpatterns = [
    path("", views.main, name='root'),
    path("upload/", views.upload, name='upload'),
    path("pictures/", views.pictures, name='pictures'),
    path("pictures/edit/<int:pic_id>", views.edit, name='edit'),
    path("pictures/remove/<int:pic_id>", views.remove, name='remove'),
]

m09_13_01_django/killer_instagram/killer_instagram/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_instagram.urls")),
    path("users/", include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

m09_13_01_django/killer_instagram/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("signin/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

m09_13_01_django/killer_instagram/app_instagram/models.py
import os
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


def update_filename(instance, filename):
    upload_to = f'uploads'
    ext = filename.split('.')[-1]
    filename = f"{uuid4().hex}.{ext}"
    return os.path.join(upload_to, filename)


# Create your models here.
class Picture(models.Model):
    description = models.CharField(max_length=150, blank=True)
    path = models.ImageField(upload_to=update_filename)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)

    def __str__(self):
        return f'{self.user.username}({self.user.email}): {self.path}'

m09_13_01_django/killer_instagram/users/models.py
from django.db import models

# Create your models here.

m09_13_01_django/killer_instagram/app_instagram/forms.py
from django.forms import ModelForm, ImageField, CharField, FileInput, TextInput

from .models import Picture


class PictureForm(ModelForm):
    description = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    path = ImageField(widget=FileInput(attrs={"class": "form-control"}))

    class Meta:
        model = Picture
        fields = ['description', 'path']

m09_13_01_django/killer_instagram/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=150, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")

m09_13_01_django/killer_instagram/app_instagram/views.py
import os

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .forms import PictureForm
from .models import Picture


# Create your views here.
def main(request):
    return render(request, 'app_instagram/index.html', context={"title": "Web 9 Group!"})


@login_required
def upload(request):
    form = PictureForm(instance=Picture())
    if request.method == "POST":
        form = PictureForm(request.POST, request.FILES, instance=Picture())
        if form.is_valid():
            pic = form.save(commit=False)
            pic.user = request.user
            pic.save()
            return redirect(to="app_instagram:pictures")
    return render(request, 'app_instagram/upload.html', context={"title": "Web 9 Group!", "form": form})


@login_required
def pictures(request):
    pictures = Picture.objects.filter(user=request.user).all()
    return render(request, 'app_instagram/pictures.html',
                  context={"title": "Web 9 Group!", "pictures": pictures, "media": settings.MEDIA_URL})


@login_required
def remove(request, pic_id):
    picture = Picture.objects.filter(pk=pic_id, user=request.user)
    try:
        os.unlink(os.path.join(settings.MEDIA_ROOT, str(picture.first().path)))
    except OSError as e:
        print(e)
    picture.delete()
    return redirect(to="app_instagram:pictures")


@login_required
def edit(request, pic_id):
    if request.method == 'POST':
        description = request.POST.get('description')
        Picture.objects.filter(pk=pic_id, user=request.user).update(description=description)
        return redirect(to="app_instagram:pictures")

    picture = Picture.objects.filter(pk=pic_id, user=request.user).first()
    return render(request, "app_instagram/edit.html",
                  context={"title": "Web 9 Group!", "pic": picture, "media": settings.MEDIA_URL})

m09_13_01_django/killer_instagram/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


# Create your views here.


class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="app_instagram:root")
        return super(RegisterView, self).dispatch(request, * args, ** kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f'Вітаю {username}. Ваш аккаунт успішно створено')
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

m09_13_01_django/killer_instagram/app_instagram/templates/app_instagram/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_instagram:pictures' %}">Pictures</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_instagram:upload' %}">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">SignIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">SignUp</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

m09_13_01_django/killer_instagram/app_instagram/templates/app_instagram/edit.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Upload file</h1>
<form action="{% url 'app_instagram:edit' pic.id %}" method="post">
    {% csrf_token %}
    <img src="{{media}}{{pic.path}}" width="350" height="350" alt="pic">
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input type="text" class="form-control" value="{{pic.description}}" name="description">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

m09_13_01_django/killer_instagram/app_instagram/templates/app_instagram/index.html
{% extends "app_instagram/base.html" %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
    <img class="d-block mx-auto mb-4" src="#" alt="" width="72" height="57">
    <h1 class="display-5 fw-bold">Centered hero</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most
            popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system,
            extensive prebuilt components, and powerful JavaScript plugins.</p>
<!--        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">-->
<!--            <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Primary button</button>-->
<!--            <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>-->
<!--        </div>-->
    </div>
</div>

{% endblock %}

m09_13_01_django/killer_instagram/app_instagram/templates/app_instagram/pictures.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Your pictures</h1>
<div class="row">
    {% for pic in pictures %}
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <img src="{{media}}{{pic.path}}" class="card-img-top" alt="pic">
            <div class="card-body">
                <p class="card-text">{{pic.description}}</p>
                <a href="{% url 'app_instagram:edit' pic.id %}" class="btn btn-info">Edit</a>
                <a href="{% url 'app_instagram:remove' pic.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>

    {% endfor %}

</div>
{% endblock %}

m09_13_01_django/killer_instagram/app_instagram/templates/app_instagram/upload.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Upload file</h1>
<form action="{% url 'app_instagram:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Description</label>
        {{form.description}}
    </div>
    <div class="mb-3">
        <label class="form-label">Picture</label>
        {{form.path}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

m09_13_01_django/killer_instagram/users/templates/users/logout.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Ви вже пішли? Ну і фіг з вами ми не будемо сумувати?</h1>
{% endblock %}

m09_13_01_django/killer_instagram/users/templates/users/password_reset.html
{% extends "app_instagram/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

m09_13_01_django/killer_instagram/users/templates/users/password_reset_complete.html
{% extends "app_instagram/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

m09_13_01_django/killer_instagram/users/templates/users/password_reset_confirm.html
{% extends "app_instagram/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

m09_13_01_django/killer_instagram/users/templates/users/password_reset_done.html
{% extends "app_instagram/base.html" %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

m09_13_01_django/killer_instagram/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

m09_13_01_django/killer_instagram/users/templates/users/signin.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>SignUp</h1>

<!-- Виводимо Flash сповіщення-->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<!--Обробляємо помилки форми які не відносяться до полів -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.non_field_errors}}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sing In</button>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

m09_13_01_django/killer_instagram/users/templates/users/signup.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>SignUp</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">First Name</label>
            {{form.first_name}}
        </div>
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Last Name</label>
            {{form.last_name}}
        </div>
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Confirm password</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sing Up</button>
</form>
{% endblock %}